[package]
name = "solana_ders"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.1"
borsh-derive = "0.9.1"
solana-program = "=1.18.14"
thiserror = "1.0.24"



[lib]
name = "solana_ders"
crate-type = ["cdylib", "lib"]

[features]
test-bpf = []